# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Build Secrets
      env:
        QT_DEBUG_PLUGINS: 1
        BASEURL: ${{ secrets.BASEURL }}
        APIKEY: ${{ secrets.SECRET_API_KEY }}
        IDENTIFIER: ${{ secrets.IDENTIFIER }}
        PASSWD: ${{ secrets.PASSWD }}
      run: |
        echo '[secrets]' >> config/app.config
        echo 'baseurl = "'$BASEURL'"' >> config/app.config
        echo 'apikey = "'$APIKEY'"' >> config/app.config
        echo 'identifier = "'$IDENTIFIER'"' >> config/app.config
        echo 'passwd = "'$PASSWD'"' >> config/app.config
    - name: Install dependencies
      run: |
        sudo apt update && sudo apt install --yes libgl1-mesa-dev libxkbcommon-x11-0
        python -m pip install --upgrade pip
        pip install flake8 pytest pyside6 pytest-qt
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        python -m pytest tests/test_functions.py
